title: Inside the mind of thegreatparadox
email: kavish.bhathija@gmail.com
description: # this means to ignore newlines until "baseurl:"
  The purpose of the existence of this blog is to serve as my personal extempore diary entry. This is a one-stop place for your daily fix of honesty. 
  The tone of the blog will be similar to how Jack kerouac (fame of On the road) writes. As the title of this blog suggests, this blog is a glimpse of 
  how my grey cells react to everyday life. Yes you guessed this right, this blog is my therapy outlet and only I am allowed to have the teddy in the circle. 
  I will be writing about everything from technology, privacy, mental health, monologues about life to fitness.
     
baseurl: "/thegreatparadox" # the subpath of your site, e.g. /blog
url: "theycallmekavish.com" # the base hostname & protocol for your site, e.g. http://example.com
# Social Profiles
twitter_username:   dagreatparadox
github_username:    kavishb12
facebook_username:  kavish.bhathija@gmail.com
linkedin_username:  kavish.bhathija

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
remote_theme: BlackrockDigital/startbootstrap-clean-blog-jekyll
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
